package com.mycompany.restaurantmanager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Emanuele
 */
public class Frame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frame.class.getName());

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane4 = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jEditorPane5 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Aggiungi");

        jButton4.setText("Rimuovi");

        jScrollPane2.setViewportView(jEditorPane1);

        jTabbedPane1.addTab("Menu", jScrollPane2);

        jScrollPane4.setViewportView(jEditorPane3);

        jTabbedPane1.addTab("Prenotazioni", jScrollPane4);

        jScrollPane5.setViewportView(jEditorPane4);

        jTabbedPane1.addTab("Gestione menu", jScrollPane5);

        jScrollPane6.setViewportView(jEditorPane5);

        jTabbedPane1.addTab("Gestione Tavoli", jScrollPane6);

        jEditorPane2.setContentType("text/html"); // NOI18N
        jEditorPane2.setText("Ecco un codice HTML perfetto per fare una prova su NetBeans all'interno del tuo JEditorPane.  Ho creato una piccola e graziosa pagina di benvenuto per un immaginario \"Cat Cafè\". Visto che Java Swing (JEditorPane) usa un motore HTML un po' datato (HTML 3.2), ho scritto il codice usando tecniche e stili \"vecchia scuola\" (come l'uso delle tabelle per centrare gli elementi e il tag <hr>). In questo modo, sei sicuro al 100% che NetBeans lo leggerà e lo visualizzerà correttamente senza strani difetti visivi.  Il Codice HTML di Prova Copia tutto questo blocco e incollalo nella proprietà text del tuo JEditorPane in NetBeans (esattamente come ti ho spiegato nel Metodo 1 della risposta precedente), oppure usalo come stringa nel tuo codice Java:  HTML <html>   <body style=\"font-family: Arial, sans-serif; background-color: #FFF0F5; text-align: center; margin: 10px;\">          <h1 style=\"color: #FF69B4;\">Benvenuti al Cat Cafè! 🐾☕</h1>          <hr color=\"#FFB6C1\" width=\"80%\">          <p style=\"color: #555555; font-size: 14px;\">       Il posto perfetto dove gustare un <b>ottimo caffè</b> in compagnia dei nostri amici felini. Rilassati e goditi la tua pausa!     </p>          <h3 style=\"color: #C71585;\">I nostri servizi:</h3>          <table align=\"center\" width=\"70%\" border=\"0\" cellpadding=\"5\">       <tr>         <td align=\"center\" bgcolor=\"#FFFFFF\" style=\"color: #333;\">🍰 Pasticceria Artigianale</td>       </tr>       <tr>         <td align=\"center\" bgcolor=\"#FFE4E1\" style=\"color: #333;\">🐈 Area Relax con i Gatti</td>       </tr>       <tr>         <td align=\"center\" bgcolor=\"#FFFFFF\" style=\"color: #333;\">📶 Wi-Fi Veloce e Gratuito</td>       </tr>     </table>          <br>          <p style=\"color: #FF1493;\">       <i>Aperto tutti i giorni dalle 08:00 alle 20:00</i>     </p>    </body> </html>");
        jEditorPane2.setToolTipText("");
        jScrollPane3.setViewportView(jEditorPane2);

        jTabbedPane1.addTab("Tavoli", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 734, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addContainerGap())
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frame().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JEditorPane jEditorPane4;
    private javax.swing.JEditorPane jEditorPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
