spring.datasource.url=jdbc:mysql://localhost:3306/ristorante_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Dice a Java di creare e aggiornare da solo le tabelle nel DB quando premi Play
spring.jpa.hibernate.ddl-auto=none

# Mostra nella console in basso i comandi SQL che Java lancia (comodo per vedere se inserisce i tavoli)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect